[package]
name = "tensor"
version = "0.0.0"
edition = "2021"
authors = ["YdrMaster <ydrml@hotmail.com>"]

[dependencies]
ggus.workspace = true
operators = { workspace = true, features = ["common-cpu"] }
ndarray-layout.workspace = true
rand = "0.8"
